{% set version = "1.3.2" %}

package:
  name: shellingham
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/shellingham/shellingham-{{ version }}.tar.gz
  sha256: 576c1982bea0ba82fb46c36feb951319d7f42214a82634233f58b40d858a751e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - shellingham
    - shellingham.posix

about:
  home: https://pypi.org/project/shellingham
  license: ISC (ISCL)
  license_file: LICENSE
  summary: Tool to Detect Surrounding Shell

extra:
  recipe-maintainers:
    - ocefpaf
