travis:
  secure:
    BINSTAR_TOKEN: eq4mMp7DFDMijoyf+/ljGpHQpx2FquUFJXNSrYbwkvI6qEM4cesNUpcmw/0AuAHLvaKA18Ha5jzA2THNRG7kCJbBlFnuSh5m3ijAnkatZMweS1UGYoiG9f1q8/ZbUUhQ7vVgGZM1yM59bmRV1ctYGW54cPzqaBiht2Nm/9uVs9KwTbUYRkoOHb/xrTB+dDt6DjqvYxp6Xwek6fi4xFhi6/HbxWF4vwPtLHFuPT0RMRlE672vUItZRNJjsd8h35uDX/ROGBrD0CoDsFnkEqbFseTtDAEVsh4qyDBGQJ2KJorRuJbzS58X2tBjnX72MO93Qpdss8EwNwKSpfQFIFqIC7K2lzmaIHG7+ml220mRy5BDk4H4IlJ2lW/kNHvwuuZhNhaDehWxxbwZ7/lOH8K4yM5pfOsI7ImxO/QjllNu8NRFTO/3Pkow3P2GCzw+1VzL2kFEhH/EBpRwf+ybDYLq7fE7/wRUjyYxvXoPuS9lbBHI7ZvCwRrFIVNZe+sKMFvPQmxxglrC8PsX+balbHKML9etznZzK5+Bpl1ryj/nrHm80/vQwSpwBCg8rgtvXMyXl07Y5Hh7GpReP//pVJ0TljfpdwncYV3H0P6FJu9UJhhgiVsZs1bNzD4shT80ouac6UrgoMhEH3Va9lIxqk5fFPQqs4wwuuBImH5m3zABqHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
